// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3LPKySu53qoZQ9Lebxkp5inkoPs7O84E',
    appId: '1:1021996917870:web:7e8b4a6332924166cab27f',
    messagingSenderId: '1021996917870',
    projectId: 'chatify-realtime-d4bd4',
    authDomain: 'chatify-realtime-d4bd4.firebaseapp.com',
    storageBucket: 'chatify-realtime-d4bd4.appspot.com',
    measurementId: 'G-DQ8D39FXDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ooyJmDux1Z6104wBirQ9KWs6kT3C7hc',
    appId: '1:1021996917870:android:0e6a80150a49775ecab27f',
    messagingSenderId: '1021996917870',
    projectId: 'chatify-realtime-d4bd4',
    storageBucket: 'chatify-realtime-d4bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWgi0mWRylFJZ70SlIHcpyJqLeuG4pTo',
    appId: '1:1021996917870:ios:9ee357f4d811946bcab27f',
    messagingSenderId: '1021996917870',
    projectId: 'chatify-realtime-d4bd4',
    storageBucket: 'chatify-realtime-d4bd4.appspot.com',
    iosBundleId: 'com.example.chatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFWgi0mWRylFJZ70SlIHcpyJqLeuG4pTo',
    appId: '1:1021996917870:ios:c3e9f9b2c5c5a0cecab27f',
    messagingSenderId: '1021996917870',
    projectId: 'chatify-realtime-d4bd4',
    storageBucket: 'chatify-realtime-d4bd4.appspot.com',
    iosBundleId: 'com.example.chatt.RunnerTests',
  );
}
